In [13]:
# 导入算法包以及数据集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB

In [14]:
# 载入数据
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target) 

In [15]:
mul_nb = GaussianNB()
mul_nb.fit(x_train,y_train)

GaussianNB(priors=None)

In [16]:
print(classification_report(mul_nb.predict(x_test),y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.92      0.96        13
          2       0.92      1.00      0.96        11

avg / total       0.98      0.97      0.97        38



In [17]:
print(confusion_matrix(mul_nb.predict(x_test),y_test))

[[14  0  0]
 [ 0 12  1]
 [ 0  0 11]]
